# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathToSolution: 'PizzaBoxMVC/'
  pathToTest: 'PizzaBoxMVC/PizzaBox.Test'
  pathToProject: 'PizzaBoxMVC/PizzaBox.WebUI'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'rjsonarcloud'
    organization: 'canlasrjdotnet'
    scannerMode: 'MSBuild'
    projectKey: 'rjsonar'

- script:
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathToSolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
  workingDirectory: $(pathToSolution)
  displayName: 'dotnet test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(pathToTest)'
    workingDirectory: '$(pathToSolution)'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: SonarCloudAnalyze@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(pathToSolution)'
  displayName: 'dotnet publish + zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(6701e12e-66a1-4ee7-b304-8f8292024374)'
    appType: 'webAppLinux'
    appName: 'pizzariamvc'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'